[package]
name = "noteshrink-rs"
version = "0.2.0"
authors = ["Oussama Moutaoikil <m.oussama@proton.me>"]
description = "Convert scanned, handwritten notes to compact, beautiful images and PDFs."
repository = "https://github.com/singularhomology/noteshrink-rs.git"
readme = "README.md"
license = "MIT"
edition = "2021"
keywords = ["image-processing", "notes", "scan", "quantization", "pdf"]
categories = ["command-line-utilities", "multimedia::images"]

[lib]
name = "noteshrink_rs"
path = "src/lib.rs"

[[bin]]
name = "noteshrink-rs"
path = "src/main.rs"

[dependencies]
ndarray = "0.16.1"
nshare = "0.10.0"
image = "0.25.10"
rand = "0.9.1"
clap = { version = "4.6.7", features = ["derive"] }
kmeans = "2.0.2"
indicatif = "0.18.6"
colored = "3.1.1"
exec_time = "0.1.7"
rayon = "1.10"
